#ifndef __WIREFRAME_H__
#define __WIREFRAME_H__

#include "constants.h"

namespace gui
{

struct wf_element_t
{
    int16_t x, y, width, height;
};

struct wf_home_screen_t
{
    wf_element_t macro_buttons[MACRO_PLACE_OPTIONS] = {
        {HOME_SCREEN_COL_1_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_2_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_3_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_4_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_1_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_2_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_3_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT}
    };

    wf_element_t menu_button = {
        HOME_SCREEN_COL_4_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT};
};

struct wf_main_menu_t
{
    wf_element_t load_button = {
        MAIN_MENU_COL_1_X, MAIN_MENU_ROW_Y, DEFAULT_MENU_BUTTON_WIDTH, DEFAULT_MENU_BUTTON_HEIGHT};
    wf_element_t back_button = {
        MAIN_MENU_COL_2_X, MAIN_MENU_ROW_Y, DEFAULT_MENU_BUTTON_WIDTH, DEFAULT_MENU_BUTTON_HEIGHT};
};

struct wf_macro_select_t
{
    wf_element_t macro_select_options[MACRO_SELECT_OPTIONS] = {
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_1_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT},
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_2_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT},
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_3_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT},
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_4_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT},
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_5_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT},
        {MACRO_SELECT_OPTION_X, MACRO_SELECT_OPTION_6_Y, MACRO_SELECT_OPTION_WIDTH, MACRO_SELECT_OPTION_HEIGHT}};

    wf_element_t scroll_left_button = {
        MACRO_SELECT_SCROLL_LEFT_X, MACRO_SELECT_SCROLL_Y, DEFAULT_MENU_BUTTON_WIDTH, DEFAULT_MENU_BUTTON_HEIGHT};
    wf_element_t scroll_right_button = {
        MACRO_SELECT_SCROLL_RIGHT_X, MACRO_SELECT_SCROLL_Y, DEFAULT_MENU_BUTTON_WIDTH, DEFAULT_MENU_BUTTON_HEIGHT};
    wf_element_t confirm_button = {
        MACRO_SELECT_BACK_X, MACRO_SELECT_SCROLL_Y, DEFAULT_MENU_BUTTON_WIDTH, DEFAULT_MENU_BUTTON_HEIGHT};
};
} // namespace gui
#endif // __WIREFRAME_H__