#ifndef __WIREFRAME_H__
#define __WIREFRAME_H__

#include "constants.h"

namespace gui
{

struct wf_element_t
{
    int16_t x, y, width, height;
};

struct wf_home_screen_t
{
    wf_element_t macro_buttons[MACRO_PLACE_OPTIONS] = {
        {HOME_SCREEN_COL_1_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_2_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_3_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_4_X, HOME_SCREEN_ROW_1_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_1_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_2_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT},
        {HOME_SCREEN_COL_3_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT}
    };

    wf_element_t menu_button = {
        HOME_SCREEN_COL_4_X, HOME_SCREEN_ROW_2_Y, DEFAULT_MACRO_BUTTON_WIDTH, DEFAULT_MACRO_BUTTON_HEIGHT};
};

} // namespace gui
#endif // __WIREFRAME_H__